org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.249
loader_version_range=[1,)

mod_id=equivalent_legacy
mod_name=Equivalent Legacy
mod_license=MIT
mod_framework=neoforge
mod_version=1.0.0
mod_group_id=com.skd.equivalentlegacy
mod_curseforge_project_id=1632317

jei_version=19.21.2.313
wthit_version=12.5.1
badpackets_version=0.8.2
